### ISSUE TITLE
Cryptographic hash function algorithm

### ISSUE THREAD

**Issue by MTanasan** [nicoDs96/Document-Similarity-using-Python-and-PySpark#1]
Hi,
Your work has been wonderful. 
Can I ask you to send me the **article on the **Cryptographic hash function algorithm**** that you use to implement the project?

**Comment by nicoDs96** [comment]
Hi, thank you very much I am really happy you appreciate the project. 
About the crypto-hash, as you can see at [LSH folder](https://github.com/nicoDs96/Document-Similarity-using-Python-and-PySpark/blob/master/LSH/DM_HW2_Ex2.ipynb) in chapter HashFamily it is a simple sha-1. The definition of sha 1 is a [NIST publication](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.180-4.pdf). I am not sure however if I understood your question and you actually need the sha1 paper or if you need something about applicability of crypto hash in the similarity search. If the latter is what you are asking for, there are no constraints on the hash functions you can use, crypto hash are only slower but less likely to generate collisions, even if for Sha1 collisions have been found

**Comment by MTanasan** [comment]
I mean that sha-1 hash coding maintain similarity in new space?

**Comment by MTanasan** [comment]
Hi, thank you very much I am really happy you appreciate the project.
About the crypto-hash, as you can see at LSH folder in chapter HashFamily it is a simple sha-1. The definition of sha 1 is a NIST publication. I am not sure however if I understood your question and you actually need the sha1 paper or if you need something about applicability of crypto hash in the similarity search. If the latter is what you are asking for, there are no constraints on the hash functions you can use, crypto hash are only slower but less likely to generate collisions, even if for Sha1 collisions have been found

**Comment by MTanasan** [comment]
I want to find out that does sha-1 hash coding maintains similarity in the new space?

**Comment by nicoDs96** [comment]
@MTanasan ok now I got it, thank you for the patience. 
There is a theorem stating that the a **minhash** function for two sets equals the Jaccard similarity for those sets under certain conditions (or something like that, it is quite a bit I don't touch this stuff, don't blame on me if i am not precise). The minhash technique is independent from the family of hash functions used, it is a general technique  and it only matters that an hash function is used. 
I suggest you to start from [wikipedia](https://en.wikipedia.org/wiki/MinHash) and follow its references for the articles. Also there is a nice blog post about the topic [here](https://aksakalli.github.io/2016/03/01/jaccard-similarity-with-minhash.html). 
Hope this is what you where looking for!
