### ISSUE TITLE
Minhash not Accurate

### ISSUE THREAD

**Issue by UUronb** [nicoDs96/Document-Similarity-using-Python-and-PySpark#2]
I ran your code for minhashing using your "Lorem ipsum..." doc examples but bumped the value on the minhashSigner up to 1200 for better accuracy. It consistently returns values centered around .70 rather than the true JS of .83. It looks like you also got a value closer to .7 rather than the true JS when you ran it. I tried it on another sample document comparison as well and got values consistently .1 below the true JS. From my understanding, minhash should return values centered around the true value. Running minhash multiple times on the same docs and averaging should be close to the true value but this doesn't appear to be happening here. Great documentation and code fills an implementation need, just wondering if there's something that's causing the minhash values to be inaccurate. Thanks for your work on this!

**Comment by nicoDs96** [comment]
Hi @UUronb , thank you for writing, I'm happy that you have appreciated the job. 
About your question: as you know, minhash and LSH are approximation. For me, an error of 0.1 was a valid approximation. If for your use case it is not, you might tune the parameters (shingle size and minhash size) on a sample dataset like this:
```python
shingle_sizes = [3,6,9,20,30]
minhash_sizes = [3,6,9,20,30,100]
res = {}
for ss in shingle_sizes:
  res[f'{ss}']={}
```
and then 
```python
for ss in shingle_sizes:
     for ms in minhash_sizes:
             shingler_inst = shingler(ss)
             shinglings = shingler_inst.get_shingles(doc)
             shinglings2 = shingler_inst.get_shingles(doc2)
             minhash_sig = minhashSigner(ms).compute_signature_matrix([shinglings,shinglings2])
             set_sig_1 = set(minhash_sig[0])
             set_sig_2 = set(minhash_sig[1])
             jaccard_similarity_sig = len(set_sig_1.intersection(set_sig_2))/len(set_sig_1.union(set_sig_2))
             jaccard_similarity_shingle_set = len(set(shinglings).intersection(shinglings2))/len(set(shinglings).union(shinglings2))
             res[f'{ss}'][f'{ms}'] = [jaccard_similarity_sig, jaccard_similarity_shingle_set]
```
Using the lorem ipsium test doc you obtain something like:
```python
{
	'3': {
		'3': [1.0, 0.8702064896755162], 
		'6': [1.0, 0.8702064896755162], 
		'9': [0.5, 0.8702064896755162], 
		'20': [0.7391304347826086, 0.8702064896755162], 
		'30': [0.7142857142857143, 0.8702064896755162], 
		'100': [0.7699115044247787, 0.8702064896755162]}, 
	'6': {
		'3': [0.5, 0.8352402745995423], 
		'6': [0.7142857142857143, 0.8352402745995423], 
		'9': [0.8, 0.8352402745995423], 
		'20': [0.6666666666666666, 0.8352402745995423], 
		'30': [0.8181818181818182, 0.8352402745995423], 
		'100': [0.8018018018018018, 0.8352402745995423]}, 
	'9': {
		'3': [1.0, 0.8288888888888889], 
		'6': [0.7142857142857143, 0.8288888888888889], 
		'9': [0.8, 0.8288888888888889], 
		'20': [0.6, 0.8288888888888889], 
		'30': [0.875, 0.8288888888888889], 
		'100': [0.639344262295082, 0.8288888888888889]}, 
	'20': {
		'3': [0.5, 0.8246013667425968], 
		'6': [1.0, 0.8246013667425968], 
		'9': [0.8, 0.8246013667425968], 
		'20': [0.6666666666666666, 0.8246013667425968], 
		'30': [0.6666666666666666, 0.8246013667425968], 
		'100': [0.680672268907563, 0.8246013667425968]}, 
	'30': {
		'3': [0.2, 0.8205128205128205], 
		'6': [1.0, 0.8205128205128205], 
		'9': [0.6363636363636364, 0.8205128205128205], 
		'20': [0.7391304347826086, 0.8205128205128205], 
		'30': [0.7142857142857143, 0.8205128205128205], 
		'100': [0.6949152542372882, 0.8205128205128205]}
}
```
And shingle size 6 or 9, minshash 9 or 30 might be more valid choices. 
Note also that, as I know, this is intended for very large documents, using it for small strings is only a test.
I hope this answers to your question, if not let me know.


Have a nice day!

**Comment by UUronb** [comment]
Thanks for the quick reply. Are you running the code as listed in your github? You seem to be getting accurate results but when I run with the code you have posted, it returns something lower (for example, at 6 shingles the lorem ipsum is centered around .72 (running multiple iterations at the same shingle and minhash size and taking the average) but yours are centered around the true value of .83. Wondering if maybe the github has a bug that needs to be updated? I'm running in Colab if that matters. I imported it exactly as you have it on DM_HW2_Ex2.ipynb and used the below implementation:

doc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
doc2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident bla bla bla."

shingler_inst = shingler(6)        
shinglings = shingler_inst.get_shingles(doc) 
shinglings2 = shingler_inst.get_shingles(doc2)
minhash_sig = minhashSigner(60).compute_signature_matrix([shinglings,shinglings2])
set_sig_1 = set(minhash_sig[0])
set_sig_2 = set(minhash_sig[1])
jaccard_similarity_sig = len(set_sig_1.intersection(set_sig_2))/len(set_sig_1.union(set_sig_2))
print(jaccard_similarity_sig)

**Comment by nicoDs96** [comment]
I have copied snippets from the [article](https://nicods96.github.io/hi//fast-document-similarity-in-python/) linked in the readme of the repo (same code of the notebook). 
Here the complete script used to produce the benchmark above:
```python
import re
import math
import json
import hashlib
from random import randint, seed

class shingler:
    def __init__(self, k):
        if k > 0:
            self.k = int(k)
        else:
            self.k = 10   
    #inner class utility
    def process_doc(self, document):
        return re.sub("( )+|(\n)+"," ",document).lower()
    
    def get_shingles(self, document):
        shingles = set()
        document= self.process_doc(document)
        for i in range(0, len(document)-self.k+1 ):
            shingles.add(document[i:i+self.k])
        return shingles


# the family of hash functions, in this case, is the same function (sha1) applied with a different salt.
class hashFamily:
    def __init__(self, i):
        self.resultSize = 8 # how many bytes we want back
        self.maxLen = 20 # how long can our salt be (in decimal)
        self.salt = str(i).zfill(self.maxLen)[-self.maxLen:]
        
    def get_hash_value(self, el_to_hash):
        return int(hashlib.sha1(str(el_to_hash).encode('utf-8') + self.salt.encode('utf-8')).hexdigest()[-self.resultSize:], 16)
    
# NOTE: we use sha1 to avoid installing and importing an external library, sacrificing performances. No crypto-hash is required for this use case.


class minhashSigner:
    def __init__(self, sig_size):
        self.sig_size=sig_size
        # Init the hash family of functions using a random salt
        self.hash_functions = [hashFamily(randint(0,10000000000)) for i in range(0,sig_size)]
    
    def compute_set_signature(self, set_):
        set_sig = []
        for h_funct in self.hash_functions:
            min_hash = math.inf
            for el in set_:
                h = h_funct.get_hash_value(el)
                if h < min_hash:
                    min_hash = h
                
            set_sig.append(min_hash)
        
        return set_sig
    #return a list of lists that can be seen as the signature matrix
    def compute_signature_matrix(self, set_list):
        signatures = []
        for s in set_list:
            signatures.append( self.compute_set_signature(s) )
        return signatures

doc = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."

doc2 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident bla bla bla."

shingle_sizes = [3,6,9,20,30]
minhash_sizes = [3,6,9,20,30,100]
res = {}
for ss in shingle_sizes:
   res[f'{ss}']={}


for ss in shingle_sizes:
     for ms in minhash_sizes:
             shingler_inst = shingler(ss)
             shinglings = shingler_inst.get_shingles(doc)
             shinglings2 = shingler_inst.get_shingles(doc2)
             minhash_sig = minhashSigner(ms).compute_signature_matrix([shinglings,shinglings2])
             set_sig_1 = set(minhash_sig[0])
             set_sig_2 = set(minhash_sig[1])
             jaccard_similarity_sig = len(set_sig_1.intersection(set_sig_2))/len(set_sig_1.union(set_sig_2))
             jaccard_similarity_shingle_set = len(set(shinglings).intersection(shinglings2))/len(set(shinglings).union(shinglings2))
             res[f'{ss}'][f'{ms}'] = [jaccard_similarity_sig, jaccard_similarity_shingle_set]


print(json.dumps(res, indent=4))

shingler_inst = shingler(6)
shinglings = shingler_inst.get_shingles(doc)
shinglings2 = shingler_inst.get_shingles(doc2)
minhash_sig = minhashSigner(9).compute_signature_matrix([shinglings,shinglings2])
set_sig_1 = set(minhash_sig[0])
set_sig_2 = set(minhash_sig[1])
jaccard_similarity_sig = len(set_sig_1.intersection(set_sig_2))/len(set_sig_1.union(set_sig_2))
print(jaccard_similarity_sig)
> 0.8
```

![immagine](https://user-images.githubusercontent.com/49313849/216271331-583f2d20-d707-465e-b19f-a370d49a2e30.png)


NOTE: up to here the approximation is deterministic, you run multiple times for the same documents and you will obtain the exact same approximate JS value all the time.

**Comment by nicoDs96** [comment]
ps.  I suggest you to take a look at [datasketch](http://ekzhu.com/datasketch/lsh.html), that is way more robust than this experiment.

**Comment by UUronb** [comment]
Thanks for going over that with me. We seem to be running the same code so not sure why my output doesn't match. Strange. This was more for learning to wrap my head around minhash and how it works so this has still been very helpful. I'll dive into LSH and more practical applications here soon so will definitely use datasketch. Thanks for the recommendation.
